---

version: '3.8'

services:
  postgres:
    container_name: kinesis-butler-postgres
    image: postgres:13.3
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    networks:
      - all

volumes:
  postgres:

networks:
  all:
